# Generated by Django 5.0.4 on 2024-04-15 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0002_rename_assigned_to_user1_assigned_pm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='assigned_PM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developers_pm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user1',
            name='assigned_TL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developers_tl', to=settings.AUTH_USER_MODEL),
        ),
    ]
