# Generated by Django 5.0.4 on 2024-04-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_alter_user1_assigned_pm_alter_user1_assigned_tl'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, default='assigned', max_length=100, null=True),
        ),
    ]
