# Generated by Django 5.0.4 on 2024-04-17 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0004_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
